# Generated by Django 3.2.3 on 2021-05-26 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_channel_message_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='pub_date',
            new_name='date_time',
        ),
    ]
